---
title: 'ggalchemy: Combining plots with cowplot and patchwork'
author: ''
date: '2018-10-27'
draft: true
slug: ggalchemy-combining-plots-with-cowplot-and-patchwork
categories: []
tags:
  - r
header:
  caption: ''
  image: ''
---


```{r}
library(tidyverse)

diabetes <- read_csv("http://biostat.mc.vanderbilt.edu/wiki/pub/Main/DataSets/diabetes.csv")
diabetes <- diabetes %>% 
  rename(sex = gender)

diabetes
```

# patchwork: Compose ggplots

```{r}
library(patchwork)
library(cowplot)
```


## combine plots horizontally: `+`
## combine plots vertically: `/`
## group plots: `()`
## control layout: `plot_layout()`

## Assess the relationship between sex, a1c, waist to hip ratio, and body frame

```{r}
label_frames <- function(lbl) paste(lbl, "\nframe")

theme_multiplot <- function(base_size = 14, ...) {
  theme_minimal(base_size = base_size, ...) %+replace%
    theme(
      panel.grid.major.x = element_blank(),
      panel.grid.minor.x = element_blank(),
      panel.grid.minor.y = element_blank(),
      legend.position = "none"
    )
}
```

## density plot

```{r}
plot_a <- diabetes %>% 
  ggplot(aes(waist/hip, fill = sex)) + 
    geom_density(
      col = "white", 
      alpha = .7, 
      size = .75
     ) + 
    theme_multiplot() +
    scale_fill_manual(values = c("#009E73", "#0072B2")) + 
    annotate(
       "text", 
       x = c(.75, .98), 
       y = c(5, 5.70), 
       label = c("female", "male"), 
       color = c("#009E73", "#0072B2"),
       size = 5
      ) + 
    labs(tag = "A") 

plot_a
```

## boxplot

```{r}
plot_b <- diabetes %>% 
  drop_na(frame) %>% 
  ggplot(aes(fct_rev(frame), waist/hip, fill = sex, col = sex)) + 
    geom_boxplot(
      outlier.color = NA, 
      alpha = .8, 
      width = .5
     ) +
    theme_multiplot() %+replace%
    theme(axis.title.x = element_blank()) + 
    scale_x_discrete(labels = label_frames) + 
    scale_color_manual(values = c("#009E73", "#0072B2")) + 
    scale_fill_manual(values = c("#009E7370", "#0072B270")) + 
    labs(tag = "B")

plot_b
```

## scatter plot with regression lines

```{r}
plot_c <- diabetes %>% 
  drop_na(frame) %>% 
  ggplot(aes(waist/hip, glyhb,  col = sex)) +
    geom_point(
      shape = 21, 
      col = "white", 
      fill = "grey80", 
      size = 2.5
     ) + 
    geom_smooth(
      method = "lm", 
      se = FALSE, 
      size = 1.3
    ) + 
    theme_minimal(base_size = 14) +
    theme(
      legend.position = c(1, 1.25),
      legend.justification = c(1, 0),
      legend.direction = "horizontal",
      panel.grid.minor.x = element_blank(),
      panel.grid.minor.y = element_blank()
     ) + 
    facet_wrap(~fct_rev(frame), labeller = as_labeller(label_frames)) +
    labs(tag = "C", y = "hemoglobin a1c") + 
    scale_y_log10(breaks = c(3.5, 5.0, 7.0, 10.0, 14.0)) +
    scale_color_manual(name = "", values = c("#009E73FF", "#0072B2FF")) +
    guides(color = guide_legend(override.aes = list(size = 5)))
```

```{r, echo=FALSE}
plot_c
```

```{r, fig.height=4.75}
(plot_a + plot_b) / plot_c
```

## Combining patchwork and cowplot

```{r}
legend <- ggdraw() + 
  get_legend(plot_c + theme(legend.position = "bottom"))

  (plot_a + plot_b) / 
  (plot_c + theme(legend.position = "none")) / 
  legend + 
  plot_layout(heights = c(10, 10, 1)) +
  plot_annotation(
    "The relationship between waist/hip ratio in males and females by
      frame size", 
    theme = theme(plot.title = element_text(size = 16, face = "bold"))
  )
```


```{r}
side_plot <- plot_a + 
  theme(
    axis.line = element_blank(), 
    axis.text = element_blank(), 
    axis.title = element_blank(), 
    axis.ticks = element_blank(),
    panel.grid.major = element_blank()
   ) + 
  labs(tag = "") + 
  coord_flip()

margin_plot <- ggdraw(
  insert_yaxis_grob(
    plot_b + labs(tag = "A"), 
    side_plot, 
    position = "right"
  )
)

plot_grid(margin_plot, plot_c + labs(tag = "B"), ncol = 1)
```


```{r}
ggdraw(
  insert_yaxis_grob(
    plot_b + labs(tag = ""), 
    side_plot, 
    position = "right"
  )
)
```
